const { stamp } = require('js-automation-tools');

const randomDigits1 = stamp.getTimestamp();
const randomDigits2 = stamp.resetTimestamp();
const randomDigits3 = stamp.resetTimestamp();
const randomDigits4 = stamp.resetTimestamp();
const randomDigits5 = stamp.resetTimestamp();
const randomDigits6 = stamp.resetTimestamp();
const randomDigits7 = stamp.resetTimestamp();
const randomDigits8 = stamp.resetTimestamp();
const randomDigits9 = stamp.resetTimestamp();

let redminePage = {
    urlRedmine: 'http://demo.redmine.org/',
    emailRegularUser: `test_user_testcafe_poc${randomDigits1}@sharklasers.com`,
    passwordRegularUser: 'test_user_testcafe_poc',

    linkLogin: '.login',
    inputUsername: '#username',
    inputPassword: '#password',
    buttonLogin: '[name="login"]',
    linkRegister: '.register',
    inputUserLogin: '#user_login',
    inputUserPassword: '#user_password',
    inputUserPasswordConfirmation: '#user_password_confirmation',
    inputUserFirstName: '#user_firstname',
    inputUserLastName: '#user_lastname',
    inputUserMail: '#user_mail',
    buttonSubmit: '[value="Submit"]',
    blockNotification: '#flash_notice',
    blockLoggedAs: '#loggedas',
    linkLogout: '.logout',
    linkProjects: '#top-menu .projects',
    iconAdd: '.icon-add',
    inputProjectName: '#project_name',
    buttonCreate: '[value="Create"]',
    urlProjectSettings: `/projects/test_project${randomDigits1}/settings`,
    link2TestProject: `[href*="/projects/test_project${randomDigits2}"]`,
    link3TestProject: `[href*="/projects/test_project${randomDigits3}"]`,
    link4TestProject: `[href*="/projects/test_project${randomDigits8}"]`,
    link5TestProject: `[href*="/projects/test_project${randomDigits4}"]`,
    link6TestProject: `[href*="/projects/test_project${randomDigits5}"]`,
    link7TestProject: `[href*="/projects/test_project${randomDigits6}"]`,
    link8TestProject: `[href*="/projects/test_project${randomDigits7}"]`,
    link9TestProject: `[href*="/projects/test_project${randomDigits9}"]`,
    linkNewIssue: '.new-issue',
    inputIssueSubject: '#issue_subject',
    inputIssueDescription: '#issue_description',
    dropdownIssuePriority: '#issue_priority_id',
    optionIssuePriority: '#issue_priority_id option',
    linkIssues: '#main-menu .issues',
    linkIssueName: '.subject a',
    linkFiles: '.files',
    inputChooseFiles: 'input.file_selector',
    pathToFile: './uploads/test-file.txt',
    buttonAdd: '[value="Add"]',
    linkFileName: '.filename',
    blockDigest: '.digest',
    iconEdit: '.icon-edit',
    keyDelete: 'delete',
    urlRedmineSearch: 'http://demo.redmine.org/search',
    inputSearch: '#search-input',
    blockSearchResults: '#search-results',
    iconDelete: '.icon-del',
    blockNoData: '.nodata',
    blockFile: '.file',
    buttonAction: '.buttons a',
    dataMethodDelete: 'delete',

    textFirstNameRegularUser: 'test_user',
    textLastNameRegularUser: 'testcafe_poc',
    textAccountActivated: 'Your account has been activated. You can now log in.',
    text1ProjectName: `test_project${randomDigits1}`,
    text2ProjectName: `test_project${randomDigits2}`,
    text3ProjectName: `test_project${randomDigits3}`,
    text4ProjectName: `test_project${randomDigits8}`,
    text5ProjectName: `test_project${randomDigits4}`,
    text6ProjectName: `test_project${randomDigits5}`,
    text7ProjectName: `test_project${randomDigits6}`,
    text8ProjectName: `test_project${randomDigits7}`,
    text9ProjectName: `test_project${randomDigits9}`,
    textSuccessfulCreation: 'Successful creation.',
    text2IssueName: `Test issue ${randomDigits2}`,
    text3IssueName: `Test issue ${randomDigits3}`,
    text5IssueName: `Test issue ${randomDigits4}`,
    text6IssueName: `Test issue ${randomDigits5}`,
    text7IssueName: `Test issue ${randomDigits6}`,
    text8IssueName: `Test issue ${randomDigits7}`,
    text2IssueDescription: `Test issue description ${randomDigits2}`,
    text3IssueDescription: `Test issue description ${randomDigits3}`,
    text5IssueDescription: `Test issue description ${randomDigits4}`,
    text6IssueDescription: `Test issue description ${randomDigits5}`,
    text7IssueDescription: `Test issue description ${randomDigits6}`,
    text8IssueDescription: `Test issue description ${randomDigits7}`,
    textHigh: 'High',
    textCreated: 'created.',
    textFileName: 'test-file.txt',
    textChecksum: 'd8e8fca2dc0f896fd7cb4cb0031ba249',
    text5IssueNameUpdated: `Issue ${randomDigits4} updated`,
    text6IssueNameUpdated: `Issue ${randomDigits5} updated`,
    textNormal: 'Normal',
    textSuccessfulUpdate: 'Successful update.',
    textNoData: 'No data to display'
};

module.exports = redminePage;
